### ISSUE TITLE
Summer todo list

### ISSUE THREAD

**Issue by roualdes** [roualdes/MATH131#11]
Let's add material to this repository that would be appropriate for a follow up to the 5 week course of MATH 131.  Topics should include material that I think would be a more appropriate fit for an introduction to Python from a computer science point of view.

- [ ] classes
- [ ] functions
- [ ] closures
- [ ] local versus global state
- [ ] pass by value or reference: maybe [here](https://robertheaton.com/2014/02/09/pythons-pass-by-object-reference-as-explained-by-philip-k-dick/) or [here](https://vorakl.com/articles/py-params/)
- [ ]  position, keyword, and default arguments
- [ ] anonymous functions
- [ ] list and dict comprehensions
- [ ] control flow (if/else, for, while, continue, pass, break)
- [ ] data structures (lists, dicts, tuples)
- [ ] modules
- [ ] ...

I'd appreciate help from @annasehgal and @GOATcoder07, if y'all are willing this summer.  I've already added you both to the repository.  

If y'all have other topics you think would be good to add, please respond here and I'll add them to the list.
